# Generated by Django 5.1.6 on 2025-02-12 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('R_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('R_Name', models.CharField(max_length=255, unique=True)),
                ('R_Permissions', models.JSONField(default=list)),
                ('R_Description', models.TextField(blank=True, null=True)),
                ('R_Created_At', models.DateTimeField(auto_now_add=True)),
                ('R_Updated_At', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('T_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('T_Name', models.CharField(max_length=255)),
                ('T_Description', models.TextField()),
                ('T_Priority_Level', models.CharField(max_length=50)),
                ('T_Status', models.BooleanField(default=False)),
                ('T_Deadline', models.DateTimeField()),
                ('T_Completed', models.BooleanField(default=False)),
                ('T_Total_Volunteers', models.IntegerField()),
                ('T_Volunteers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('E_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('E_Name', models.CharField(max_length=255)),
                ('E_Description', models.TextField()),
                ('E_Start_Date', models.DateTimeField()),
                ('E_End_Date', models.DateTimeField()),
                ('E_Required_Volunteers', models.IntegerField()),
                ('E_Assigned_Volunteers', models.IntegerField(default=0)),
                ('E_Completed', models.BooleanField(default=False)),
                ('E_Total_Tasks', models.IntegerField()),
                ('E_Location', models.GenericIPAddressField()),
                ('E_Volunteers', models.JSONField(default=list)),
                ('E_Tasks', models.JSONField(default=list)),
                ('E_Image_Urls', models.JSONField(default=list)),
                ('T_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tasks', to='Vapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('V_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('V_Name', models.CharField(max_length=255)),
                ('V_Address', models.TextField()),
                ('V_Status', models.BooleanField(default=False)),
                ('V_Skills', models.TextField()),
                ('V_Availability', models.BooleanField(default=False)),
                ('V_Email', models.EmailField(max_length=254, unique=True)),
                ('V_Age', models.IntegerField()),
                ('V_Gender', models.CharField(max_length=50)),
                ('V_Image_Urls', models.URLField()),
                ('V_Phone_No', models.CharField(max_length=15)),
                ('V_Assigned_Tasks', models.JSONField(default=list)),
                ('R_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='V_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Vapp.volunteer'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('S_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('S_Name', models.JSONField(default=list)),
                ('S_Level', models.JSONField(default=list)),
                ('V_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Vapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_ID', models.CharField(max_length=100, unique=True)),
                ('E_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Vapp.event')),
                ('V_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Vapp.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='V_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='Vapp.volunteer'),
        ),
    ]
