# Generated by Django 5.1.6 on 2025-03-03 07:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('R_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('R_Name', models.CharField(max_length=255, unique=True)),
                ('R_Permissions', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('T_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('T_Name', models.CharField(max_length=255)),
                ('T_Description', models.TextField()),
                ('T_Priority_Level', models.CharField(max_length=50)),
                ('T_Status', models.BooleanField(default=False)),
                ('T_Deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('E_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('E_Name', models.CharField(max_length=255)),
                ('E_Description', models.TextField()),
                ('E_Start_Date', models.DateTimeField()),
                ('E_End_Date', models.DateTimeField()),
                ('E_Location', models.TextField()),
                ('E_Tasks', models.ManyToManyField(blank=True, related_name='events', to='Vapp.task')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('V_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('V_Name', models.CharField(max_length=255)),
                ('V_Email', models.EmailField(max_length=254, unique=True)),
                ('V_Phone_No', models.CharField(max_length=15)),
                ('V_Address', models.TextField()),
                ('V_Status', models.BooleanField(default=False)),
                ('V_Skills', models.JSONField(blank=True, default=list, null=True)),
                ('V_Availability', models.BooleanField(default=False)),
                ('V_Gender', models.CharField(max_length=50)),
                ('V_Age', models.IntegerField(blank=True, null=True)),
                ('V_Image_Urls', models.URLField(blank=True, default='', null=True)),
                ('R_ID', models.ForeignKey(blank=True, db_column='R_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vapp.role')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='V_ID',
            field=models.ForeignKey(blank=True, db_column='V_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='Vapp.volunteer'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('S_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('S_Name', models.CharField(max_length=255)),
                ('S_Level', models.CharField(max_length=50)),
                ('V_ID', models.ForeignKey(blank=True, db_column='V_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='Vapp.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('R_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('E_ID', models.ForeignKey(db_column='E_ID', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Vapp.event')),
                ('V_ID', models.ForeignKey(db_column='V_ID', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Vapp.volunteer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='E_Volunteers',
            field=models.ManyToManyField(blank=True, related_name='events', to='Vapp.volunteer'),
        ),
        migrations.AddField(
            model_name='event',
            name='V_ID',
            field=models.ForeignKey(blank=True, db_column='V_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vapp.volunteer'),
        ),
    ]
