# Generated by Django 5.1.6 on 2025-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='E_QR_Code',
        ),
        migrations.RemoveField(
            model_name='event',
            name='E_Volunteers',
        ),
        migrations.AddField(
            model_name='event',
            name='E_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='E_Required_Volunteers',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='E_Status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Upcoming', max_length=20),
        ),
    ]
