# Generated by Django 5.1.6 on 2025-03-04 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0002_remove_event_e_qr_code_remove_event_e_volunteers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='E_Required_Volunteers',
            new_name='E_Capacity',
        ),
        migrations.AddField(
            model_name='event',
            name='E_Registered_Count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('R_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Vapp.event')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='E_Volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteered_events', through='Vapp.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
