# Generated by Django 5.1.6 on 2025-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0002_alter_volunteer_v_age_alter_volunteer_v_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='V_Skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
