# Generated by Django 5.1.6 on 2025-02-24 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0003_alter_volunteer_v_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='V_ID',
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Image_Urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Required_Volunteers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Tasks',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Total_Tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Volunteers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='T_ID',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vapp.task'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='V_Image_Urls',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
