# Generated by Django 5.1.6 on 2025-03-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0003_rename_e_required_volunteers_event_e_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='E_Capacity',
            new_name='E_Required_Volunteers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='E_Registered_Count',
        ),
    ]
