# Generated by Django 5.1.6 on 2025-03-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0004_rename_e_capacity_event_e_required_volunteers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='E_Photo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='E_Required_Volunteers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='E_Volunteers',
        ),
    ]
