# Generated by Django 5.1.6 on 2025-02-25 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0004_remove_event_v_id_alter_event_e_image_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='T_ID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vapp.task'),
        ),
    ]
