# Generated by Django 5.1.6 on 2025-02-27 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0005_alter_event_t_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='E_ID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
