# Generated by Django 5.1.6 on 2025-03-04 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0005_remove_event_e_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='E_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='E_Required_Volunteers',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='E_Volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteered_events', through='Vapp.Registration', to=settings.AUTH_USER_MODEL),
        ),
    ]
