# Generated by Django 5.1.6 on 2025-02-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0006_alter_event_e_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='E_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
