# Generated by Django 5.1.6 on 2025-03-04 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0006_event_e_photo_event_e_required_volunteers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='E_Created_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
