# Generated by Django 5.1.6 on 2025-03-05 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0007_alter_event_e_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='E_Coordinators',
            field=models.ManyToManyField(blank=True, related_name='coordinated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='E_Super_Volunteers',
            field=models.ManyToManyField(blank=True, related_name='super_volunteer_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Event Organizer', 'Event Organizer'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
