# Generated by Django 5.1.6 on 2025-03-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0008_event_e_coordinators_event_e_super_volunteers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='E_Registered_Count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
