# Generated by Django 5.1.6 on 2025-03-06 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0010_eventannouncement_sampletask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='T_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='T_Name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Assigned_To',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Related_Event',
        ),
        migrations.RemoveField(
            model_name='task',
            name='T_Deadline',
        ),
        migrations.RemoveField(
            model_name='task',
            name='T_Priority_Level',
        ),
        migrations.RemoveField(
            model_name='task',
            name='T_Status',
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
