# Generated by Django 5.1.6 on 2025-03-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0011_rename_t_description_task_description_and_more'),
    ]

    operations = [
    ]
