# Generated by Django 5.1.6 on 2025-03-07 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0013_task_event_alter_task_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(db_column='E_ID', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='Vapp.event'),
        ),
    ]
