# Generated by Django 5.1.6 on 2025-03-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0017_alter_task_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Event Organizer', 'Event Organizer'), ('Admin', 'Admin'), ('Coordinator', 'Coordinator'), ('Super Volunteer', 'Super Volunteer')], max_length=20),
        ),
    ]
