# Generated by Django 5.1.6 on 2025-03-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0020_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('Volunteer', 'Volunteer'), ('Coordinator', 'Coordinator'), ('Super Volunteer', 'Super Volunteer'), ('Event Organizer', 'Event Organizer')], default='Volunteer', max_length=50),
        ),
    ]
