# Generated by Django 5.1.6 on 2025-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0021_registration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='E_End_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='E_Start_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
