# Generated by Django 5.1.6 on 2025-03-13 09:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0024_rename_certificate_id_eventcertificate_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventannouncement',
            old_name='posted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='eventannouncement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_announcements', to='Vapp.event'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('N_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to='Vapp.event')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
