# Generated by Django 5.2 on 2025-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapp', '0026_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='E_End_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_End_Time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Start_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='E_Start_Time',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
